# Generated by Django 5.2.8 on 2026-03-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('processing', 'Обработка данных'), ('completed', 'Услуга оказана')], default='new', max_length=20),
        ),
    ]
